### ISSUE TITLE
Firefox update broke colours

### ISSUE THREAD

**Issue by pointydev** [ravindUwU/firefox-refined-findbar#2]
Heya,

Upon updating to Firefox 132.0b2 (might've been before, unsure), I noticed that some colour variables have changed names. This makes the search options effectively unusable as you can't see whether or not they're selected. I believe I've fixed it at my end, but didn't know whether to PR or not since I don't think this change affects stable yet.

My changes (probably not completely right) were:
```
--button-color                  to --toolbar-color
--button-bgcolor                to --color-accent-primary
--button-hover-bgcolor          to --button-background-color-hover
--button-active-bgcolor         to --button-background-color-active
--button-primary-color          to --button-text-color-primary
--button-primary-bgcolor        to --color-accent-primary
--button-primary-hover-bgcolor  to --color-accent-primary-hover
--button-primary-active-bgcolor to --color-accent-primary-active
```

Without:
![](https://the.yog.zone/6MdEvfe.png)
With:
![](https://the.yog.zone/6LuGN5n.png)

Thanks,
Elliott

**Comment by ravindUwU** [comment]
Hi Elliott 👋
The new variables that you've mentioned above seem semantically correct; thanks for finding them! I think we should be able to safely swap them, using [`var()` with fallbacks](https://developer.mozilla.org/en-US/docs/Web/CSS/var#syntax) to reference variables that don't exist pre-132 without breaking compatibility where necessary.

I likely won't be get started on this until mid to late next week, so if you'd like to work on it I'm happy to assign this issue to you; please lmk 😄.
